### ISSUE TITLE
Bufferlist

### ISSUE THREAD

**Issue by ruddbs** [sunduk/FreeNet#1]
보내실때에는 Bufferlist를 사용하시는데 받을때는 왜 안쓰시는지 궁금합니다
원래 보낼때만 사용하는건가요???
그리고 혹시 메세지를 30000개정도가 쌓여있고 그거를 클라이언트가 서버한테 보내면
클라이언트는 보내는데 서버는 전혀 받지를 못합니다. 혹시 짐작가는 이유라도 있으시면 
말씀해주세요!!! 그러면 제가 해결해 보겠습니다!!!!
+
먼저 메세지하나를 보내고 그다음 보내기시작하니 해결이 됐습니다.!!!

**Comment by sunduk** [comment]
일단 해결 되셨다니 다행입니다.^^

Bufferlist를 받을때 안쓴 특별한 이유는 없습니다.
보낼때 쓰는건 참고 자료가 있어서 바로 적용했던 것이었습니다.
supersocket이나 다른 라이브러리를 봐도 받을때는 안쓰길래 저도 더 고민하지는 않았었네요.

메시지 30000개를 큐에 쌓아서 한꺼번에 송수신 해본 결과 제 PC에서는 이상 없이 잘 작동하였습니다.
확 늘려서 300만개정도로 해보니 메모리 할당 실패가 나긴 하더군요.^^;
(이건 나중에 고쳐야겠네요)

프로젝트에 같이 포함되어 있는 SampleServer / SampleClient로 테스트했고요,
테스트 과정은 이렇습니다.
"클라에서 채팅 메시지 30000개를 큐에 쌓아놓고 SendAsync호출 -> 서버에서 수신하여 그대로 클라에게 응답 -> 응답 메시지 개수 확인"
큐에 쌓는 부분은 CUserToken클래스의 send매소드를 약간 수정하여 30000개가 되었을 때 한방에 SendAsync하도록 했습니다.

일단 최근 커밋된 코드로 테스트하신것이 맞는지 확인 부탁드립니다.
예전 코드는 송, 수신시 버그가 좀 있었습니다.
테스트 하신 과정이나 코드를 남겨주시면 저도 확인해보도록 하겠습니다.
