### ISSUE TITLE
석현님 안녕하세요. 혹시 FreeNet 최신 수정된 사항 있으신가요?

### ISSUE THREAD

**Issue by KimDongYoungG** [sunduk/FreeNet#10]
석현님 안녕하세요. 혹시 FreeNet 최신 수정된 사항 있으신가요?
그리고 혹시 이메일 여쭤볼수있을까요?

**Comment by sunduk** [comment]
최근엔 수정사항이 없습니다.
회사도 옮기고 적응하느라 손을 못했네요.^^
이메일은 lee.seokhyun@gmail.com 입니다. (lee와 seokhyun~ 사이에 마침표 있습니다!)
