### ISSUE TITLE
안녕하세요!!

### ISSUE THREAD

**Issue by ruddbs** [sunduk/FreeNet#4]
안녕하세요 맨날 게임코디연구소에서 비회원으로 댓글 달았던 학생입니다 . 얼마전에 여기에다가
bufferlist를 물어보기도한 학생입니다. 
저는 지금 프로그래밍을 공부하는 대학교 3학년 학생입니다. 
구글링을 하다가 코드들을 찾아서 공부하고 있어요!!
사담이지만 프로그래밍 공부를 어떻게 하시는지 궁금합니다. ㅠㅠ 
저도 프로그래밍을 잘하고 싶어서요 ㅠㅠ
선생님 코드를 보면 이해는 가도 제가 아무것도 없는 상태에서 
저런 코드를 짤 수는 없을 거같아서요 ㅠㅠ 어떻게 공부해오셨는지 알려주시면 안될까요 ㅠㅠ
그리고 추가적으로 질문이 있습니다. 
일반적으로 사람들이 C++로 네트워크 서버를 만드는데 왜 C#으로 만드셨는지 궁금합니다.
성능면에서 정말로 C++이 더좋은가요?

**Comment by sunduk** [comment]
안녕하세요. github에서 다시 만나게 되어 반갑습니다.

> 구글링을 하다가 코드들을 찾아서 공부하고 있어요!!

구글링으로 코드를 찾는것도 좋은 방법이지만 그것만으로는 부족합니다.
프로그래밍 언어의 기초 문법과 응용에 익숙해 지려면 책과 함께 직접 코딩해보는 과정이 필요합니다.
기초 학습 -> 직접 타이핑 하여 코드 작성 -> 디버깅 이런 과정은 구글링보다는
기본서를 옆에 두고 직접 해보는 것이 더 좋습니다.


> 선생님 코드를 보면 이해는 가도 제가 아무것도 없는 상태에서
저런 코드를 짤 수는 없을 거같아서요 ㅠㅠ 어떻게 공부해오셨는지 알려주시면 안될까요 ㅠㅠ

저는 베이직, C언어부터 배워온 세대라 요즘 환경과는 약간 다르게 시작했습니다.
도스 환경에서 C언어로 간단한 성적처리 프로그램이나 달팽이 배열 만들기, 별 찍기 같은 기초 알고리즘 구현을 통해 프로그래밍을 시작했습니다.
그리고 고등학교때 프로그래밍 언어의 문법과 간단한 게임 같은것을 만들며 기초를 쌓아왔고요,
대학교때는 운영체제, 컴파일러, 자료구조, 데이터베이스처럼 원천적인 내용을 주로 배웠습니다.
실무에 와서는 상용 게임을 만들면서 큰 규모의 프로그램을 설계하고 코딩하는 방법과 디버깅, 최적화등을 연구하며 실제 프로젝트에 적용시키는 방법으로 학습해왔습니다.

다른 사람이 짠 코드를 보면 이해는 가도 직접 짜려면 힘든건 당연합니다.
마치 책을 읽고 이해할순 있지만 소설을 직접 쓰기는 힘든것 처럼 말이죠.
글을 잘 쓰는 작가들은 많이 읽고 쓰고, 고치고 출판하고 해본 사람들일겁니다.
프로그래밍도 많이 보고, 짜고, 고치고 한다면 누구나 잘 할 수 있게 됩니다.
단, 무조건 많이 한다기 보다 학습 방향에 대해서는 조언을 받는게 좋겠죠.

> 그리고 추가적으로 질문이 있습니다.
일반적으로 사람들이 C++로 네트워크 서버를 만드는데 왜 C#으로 만드셨는지 궁금합니다.
성능면에서 정말로 C++이 더좋은가요?

성능면에서 C++이 더 좋습니다.
**그런데 어떻게 설계 하고 코딩 하냐에 따라 다를 수 있기 때문에 무조건은 아닙니다.**
C#으로 만드는 이유는
C++보다 코딩하기 더 재밌고 편하고, 쉽고(저한테는), 컴파일도 빠르고 해서 입니다.
또한 내부적으로 IOCP방식을 사용하기 때문에 닷넷(C#)으로도 충분히 성능 좋은 서버를 만들 수 있다는 것도 장점입니다.
C++을 제대로 못쓰면 불안정한 서버를 만들 확률도 크고 이래저래 위험성이 있죠.
(포인터, 템플릿 기능이 강력하긴 하지만 어설프게 쓰면 디버깅 하다 시간 다 보낼 수도 있고요^^)
C#은 C++보단 작업 생산성도 높고 언어 차원에서 실수도 줄여주고 코딩도 좀 편한 맛이 있습니다.
서버 코드를 유니티 엔진에서도 그대로 쓸 수 있다는것 또한 매력적입니다.

더 궁금한점이 있으시면 게시판도 좋고 메일로 문의 주셔도 좋습니다.
메일은 lee.seokhyun@gmail.com 입니다.
감사합니다.

**Comment by ruddbs** [comment]
감사합니다!!!!!
