### ISSUE TITLE
Freenet 유니티 버젼에서 Heart beat 버젼 적용시키면 disconnect 현상

### ISSUE THREAD

**Issue by ilkwon** [sunduk/FreeNet#5]
안녕하세요 

그동안 감사히 잘 쓰고 있었는데요.

gamecodi 에 올라와 있는 freenet unity 버젼에서..
이번 주기적으로 Heart beat 시켜주는 버젼을 적용시키면 
Client가 접속(connect)만해도 5초? 정도 후에 Client에서 접속을 끊어버립니다..  

CFreeNetEventManager 이벤트 클래스에서 어떤 문제를 야기시키는것 같은데
확인 부탁드립니다.

혹시 제가 짠 서버/클라이언트 소스가 문제인가 싶어서
github에 올라와있는 서버/클라이언트 sample 소스로 상호 테스트 진행해보았는데
CSampleServer를 켜고 제 클라이언트를 켜도 connect후에 수초 후에 disconnect 발생합니다.

그리고 저도 원인을 찾고 해결이 되면 다시 연락 드리겠습니다.

감사합니다.

**Comment by sunduk** [comment]
안녕하세요 ilkwon님.
잘 사용하고 계신다니 제가 더 감사합니다.

코드 확인 및 샘플 서버/클라이언트로 테스트해본 결과 별다른 이상은 발견하지 못했습니다.
유니티에서도 빌드하여 에디터와 모바일에 설치하여 해봤으나 문제가 재현되지는 않았습니다.
증상으로 보아 한가지 의심되는 부분은
서버쪽은 최신 커밋으로 빌드되고 클라이언트쪽은 하트비트가 적용되지 않은 dll로 빌드된게 아닌가 싶습니다.

이번에 추가한 하트 비트는,
1. 클라측 - 주기적으로 서버로 쏘는 로직.
2. 서버측 - 일정 시간 안에 클라이언트로 부터 하트비트 패킷이 안오면 잘라버리는 로직.
이렇게 두가지 부분입니다.
따라서 서버, 클라이언트 동시에 패치 해주셔야 잘 돌아가게 되어 있습니다.
혼자서 작업하고 테스트하다 보니 미처 생각하지 못했던 부분이었네요.^^
특별한 문제가 없으시다면 서버/클라 모두 동일한 dll로 작업하시면 잘 돌아갈겁니다.

혹시 이렇게 해도 해결이 안되시면 다시 이슈 남겨주세요.

(아직 부족한점이 많은 라이브러리 입니다. 작업하시다가 이상하다 싶으시면 언제든 제보 부탁드립니다.^^ 감사합니다.)

**Comment by sunduk** [comment]
아, 그리고 한가지 참고할 부분 알려드립니다.
유니티에서는 하트비트 전송을 Update매소드에서 하도록 구현하였습니다.
원래 FreeNet라이브러리의 클라이언트쪽 코드에 닷넷 타이머로 하트비트를 전송하는 부분이 구현되어 있으나, 이것을 사용하지 않게 설정한 뒤 Update매소드에서 직접 호출해줘야 합니다.
이유는 타이머로 전송할 경우 앱이 백그라운드로 가 있는 상태에서도 하트비트가 전송되기 때문에
이를 방지하기 위함입니다.
관련 샘플 코드를 커밋해놨으니 참고해 주세요.
(viruswar/client 폴더에서 FreeNet/FreeNetUnityService.cs관련 코드들을 보시면 됩니다.)

**Comment by ilkwon** [comment]
두번째 코멘트 주신 방법으로 해결을 했습니다.
네 원래 dll은 같은버젼으로  c/s에 적용이 되어있었던터라...

Heartbeat 클래스에 auto/manual disable 관련된게 있을진 몰랐네요. ^^
일단 적용부터 해놓고 문제 발생시 해맨게 실수네요 
다음부턴 면밀히 살표보고 적용해야겠습니다.

감사합니다.

**Comment by sunduk** [comment]
잘 해결 되셔서 다행입니다.
저도 앞으로 기능 추가나 변경이 될 때 다른 분들도 참고할 수 있도록 문서화를 잘 해놓도록 하겠습니다.^^
