### ISSUE TITLE
.NET Core 2.0 지원

### ISSUE THREAD

**Issue by jacking75** [sunduk/FreeNet#6]
안녕하세요^^

FreeNet이 현재 닷넷프레임워크3.5만 지원하는데 이것을 .NET Core 2.0 지원으로 바꾸던가 혹은 솔루션 파일만 .NET Core 2.0로 설정한 것을 하나더 만들면 어떨까 합니다.
(기존 솔루션 설정에서는 .NET Core는 선택할 수 없더군요)

.NET Core 2.0가 멀티플랫폼 지원이라서 서버를 리눅스에서 운용할 수 있고, 앞으로 이쪽으로 지속적인 지원이 많을 것 같습니다. 그리고 유니티의 경우도 2017 버전부터 닷넷프레임워크 버전을 올리면서 최종적으로는 .NET Core(.NET Standard가 맞겠죠)가 중심이 되지 않을까 생각합니다.

제가 .NET Core 2.0로 새로 솔류션을 만든후 기존 프로젝트에서 파일만 가져와서 빌드해보니 어떤 문제도 없었습니다(FreeNet만 빌드했습니다)

조금만 더 작업하면 쉽게 .NET Core 2.0를 지원할 수 있어서 FreeNet의 이용 범위가 훨씬 더 넓어질 수 있다고 생각합니다

**Comment by sunduk** [comment]
안녕하세요 흥배님. 여기까지 찾아와주셔서 감사합니다.^^
FreeNet이 닷넷프레임워크 3.5만 지원하는 가장 큰 이유가 유니티 엔진과의 호환성 때문이었는데
2017에서는 4.6까지 버전업이 되었네요.
유니티 포럼을 찾아보니 보니 말씀하신대로 추후에 .Net Standard를 지원하려고 계획하는것 같습니다.

.NET Core 2.0지원은 적극적으로 진행해 보겠습니다.
사실 제가 요즘 변화되는 .NET로드맵에 대해 잘 모르고 있어서 이제야 관련 자료를 찾아본 상태입니다^^
아직도 헷갈리는게 .NET Core와 .NET Standard와의 관계가 어떻게 되는지 모르겠습니다.@_@
(.NET Standard로 빌드하면 .NET Framework, .NET Core, Mono 모두 지원하게 되는것인지요??
그렇다면 .NET Framework는 점점 사라지고 .NET Core나 .NET Standard로 바뀌어갈 분위기인 건가요?)

일단 말씀하신대로 저도 .NET Core를 설치해서 포팅해보겠습니다.
다만 유니티5를 사용하는 경우도 아직 많이 있어서 프로젝트 자체를 .NET Core로 바꾸기 보다는
말씀해주신것 처럼 .NET Core용 솔루션파일을 추가하는 방향부터 시작해보려고 합니다.
그 뒤 리눅스에서 FreeNet서버를 돌려보고 테스트해봐야 겠네요.

언제가 될진 모르겠지만 유니티에서 .NET Core나 .NET Standard를 지원하게 된다면 완전히 .NET Core 또는 .NET Standard로 갈아탈 수 있을듯 합니다.
추후 FreeNet개발 로드맵에 따라 달라질순 있겠지요.
(아직 구체적인 계획은 없습니다.)

제안 감사드리며,
지난주까지 오픈소스 공모전준비 때문에 조금 바빴었는데 이제 마무리 되어서 여유시간에 작업할 수 있을듯 합니다.
진행하다가 궁금한게 생기면 흥배님께 자주 여쭤볼테니 많은 가르침 부탁드립니다.^^
완료되면 소식 전해드리겠습니다.
감사합니다.

**Comment by jacking75** [comment]
닷넷스탠다드는 라이브러리 개발에 해당 되는 것으로 닷넷스탠다드를 지원하면 닷넷프레임워크, 닷네코어 모두를 다 지원할 수 있습니다. 
그래서 모든 닷넷을 다 지원하고 싶다면 닷넷스탠다드로 라이브러리를 만들어야 합니다.

유니티의 장래 계획은 저도 잘 모르겠지만 상식적으로 생각하면 앞으로 닷넷코어가 중심이되면서 라이브러리는 닷넷스탠다드 버전을 지원할 것 같습니다.

제 도움이 필요하면 언제든지 연락주세요^^
오픈소스 공무전도 좋은 결과 있기 바랍니다.
