### ISSUE TITLE
FreeNet 라이브러리를 유니티 클라이언트에서도 사용하나요?

### ISSUE THREAD

**Issue by jacking75** [sunduk/FreeNet#7]
제가 유니티를 사용하지 않아서 FreeNet 라이브러리를 유니티 클라이언트에서 사용하는지 잘 모릅니다^^;
만약 사용하지 않는다면 FreeNet 라이브러리 프로젝트는 서버에서만 사용하는 것으로 정해서 닷넷코어나 혹은 최신 닷넷 프레임워크를 사용하는 것이 좋지 않을까 생각합니다.

혹 FreeNet 라이브러리를 유니티 클라이언트에서 사용한다면 서버와 클라이언트에서 사용할 네트워크 라이브러리를 분리하는 것이 좋을 것 같습니다. 클라이언트는 네트워크가 고성능으로 나올 필요는 없으니 꼭 FreeNet 라이브러리를 사용할 필요는 없을 것 같습니다. 클라이언트는 일반 동기IO 소켓을 사용하는 것으로 성능에 전혀 문제가 없다고 생각합니다.
그리고 클라이언트의 소켓을 될수 있으면 간단하게 만드는 것이 클라이언트를 다루는 프로그래머가 유지 보수하기가 더 편해지지 않을까 생각합니다.

혹시 FreeNet 라이브러리의 일부 코드가 클라이언트와 같이 사용하는 부분이 있어서 FreeNet 라이브러리를 닷넷3.5로 만들었다면 간단한 코드 생성기로 FreeNet 라이브러리에서 클라이언트가 필요로 하는 부분만 클라이언트용 솔루션에 들어가도록 하면 어떨까 생각합니다

**Comment by sunduk** [comment]
FreeNet은 유니티 클라이언트에서도 사용할 수 있습니다.
처음부터 서버/클라 구분 없이 사용하고 싶어서 그렇게 방향을 잡았거든요.

핵심 로직이 정착되고 안정화 되면 서버측/클라측 구분하는 방법도 생각중입니다.
아무래도 서버쪽에는 디비 관련 모듈이라던가 그런것들이 필요할테니까요.
게다가 점점 발전하는 닷넷쪽 기술을 사용하려면 어쩔수 없이 구분해야 할것 같습니다.
