### ISSUE TITLE
성능 및 안정성 테스트로 만든 프로그램은 공유 받을 수 없을까요?

### ISSUE THREAD

**Issue by jacking75** [sunduk/FreeNet#8]
안녕하세요^^
저는 FreeNet을 .Net Core로 사용해야 할 이유가 있어서 얼마전에 fork를 한 후 수정을 하고 있습니다.
수정 후 버그가 없는지 혹은 성능에 문제가 없는지 테스트를 하고 싶은데 sunduk님의 문서를 보면 성능 및 안정성 테스트를 위해서 서버/클라이언트를 사용했더군요.

그래서 괜찮으시면 sunduk님이 사용하신 성능 및 안정성 테스트를 위해서 서버/클라이언트를 공유 받고 싶습니다. 혹시 github에 올리기 힘드시면 따로 메일로 주셔도 됩니다.

혹은 사정이 있어서 공개가 힘들다면 하지 않으셔도 괜찮습니다^^

**Comment by sunduk** [comment]
안녕하세요. 흥배님.
요새 회사일과 공모전 2차심사 준비에 바빠서 이제야 게시물을 확인했습니다.^^

클라이언트는 다른분이 만들어서 공개해놓은것을 사용했고요.
(여기 링크에 가셔서 게시물 제일 아래 64비트 버전을 받으시면 됩니다)
[http://www.cgcii.co.kr/index.php?mid=board_eLHH13&document_srl=1936](http://www.cgcii.co.kr/index.php?mid=board_eLHH13&document_srl=1936)

서버는 FreeNet프로젝트에 포함되어 있는 CSampleServer를 약간 수정해서 사용했습니다.
이전에 만들어놓은게 아마 하드에 있을텐데 찾아서 올려놓던가 보내드리던가 하겠습니다.

**Comment by jacking75** [comment]
정말 고맙습니다^^ 
바쁘시겠지만 꼭 부탁합니다

ps: 참고로 제가 가르치는 학생들이 현재 freenet으로 온라인 게임 서버를 만들고 있습니다

**Comment by sunduk** [comment]
테스트 방법을 readme에 가이드해놨고요, 관련 코드도 커밋했습니다.
변경된 부분은 크지 않기 때문에 프로젝트를 다시 받기 힘든 상황이시라면 코드를 참조하셔서 fork뜨신곳에서 직접 고치셔도 될겁니다.

간단히 알려드리면...
1. 서버에서 하트비트 끄는 기능 추가.
2. CSampleServer/Program.cs 29line 주석 제거(하트비트 끄기).
3. CSampleServer/CGameUser.cs 52, 53line 주석 제거(에코서버 기능 작동).
이렇게 세팅하신뒤 테스트하시면 됩니다.
(만약 하트비트가 없는 버전에서 테스트중이시라면 1,2번은 건너뛰셔도 되겠네요.)

말씀드린대로 테스트 클라이언트는 cgcii의것을 활용하였습니다.
이에  대한 가이드도 간략하게 올려놨으니 readme를 참조해 주세요.

ps:freenet을 사용하여 게임서버를 만들고 계신다니 정말 영광입니다.
기타 테스트에 도움이 필요하시거나 작동이 이상하다 싶으면 언제든지 말씀해 주십시오!^^

**Comment by jacking75** [comment]
잘 사용하겠습니다^^
