### ISSUE TITLE
FreeNet을 이용해서 파이썬과 데이터 송수신이 가능할까요?

### ISSUE THREAD

**Issue by chobabo** [sunduk/FreeNet#9]
파이썬에서 실행한 결과값을 윈폼으로 보내려고 하는데 FreeNet으로 가능한지 궁금합니다.

**Comment by jacking75** [comment]
윈폼이라는게 닷넷으로 만든 winform 이라면 네트워크 통신으로 데이터를 주고 받을 수 있습니다.
파이썬는 tcp 라이브러리를 사용하여 클라이언트 부분이 되고, 윈폼은 FreeNet을 사용하여 서버가 되어야겠죠.

주고 받는 데이터는 바이너리 포맷의 데이터이므로 바이너리 형식만 서로 맞추면 됩니다.
바이너리 데이터 형식은 프로토콜버퍼 라이브러리를 사용하면 쉽게 할 수 있습니다.

**Comment by chobabo** [comment]
친절한 답변 진심으로 감사드립니다.
